on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build-and-commit:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
      - uses: actions/checkout@v5
        with:
          path: "build"
      - run: |
          pushd build
          npm install
          export PR_NUMBER=${{ github.event.pull_request.number }}
          npx nuxt build --preset github-pages
          popd
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: "dist"
      - run: |
          pushd dist
          mkdir -p pr-${{ github.event.pull_request.number }}
          cp -r ../build/dist/* pr-${{ github.event.pull_request.number }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Depoly files for PR #${{ github.event.pull_request.number }}"
          git push origin gh-pages
          popd
  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
      - run: |
          rm -rf pr-${{ github.event.pull_request.number }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Remove files for PR #${{ github.event.pull_request.number }}"
          git push origin gh-pages
